package com.focustar.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WeixinCheckImei", targetNamespace = "http://service.web.dc.gionee.com/")
public interface WeixinCheckImei {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkImei", targetNamespace = "http://service.web.dc.gionee.com/", className = "com.focustar.webService.CheckImei")
	@ResponseWrapper(localName = "checkImeiResponse", targetNamespace = "http://service.web.dc.gionee.com/", className = "com.focustar.webService.CheckImeiResponse")
	public String checkImei(@WebParam(name = "arg0", targetNamespace = "") AuthInfo arg0,
			@WebParam(name = "arg1", targetNamespace = "") WeixinVO arg1);

}
