package com.focustar.webService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WeixinCheckImeiImplService service = new WeixinCheckImeiImplService();
 * WeixinCheckImei portType = service.getWeixinCheckImeiImplPort();
 * portType.checkImei(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WeixinCheckImeiImplService", targetNamespace = "http://impl.service.web.dc.gionee.com/", wsdlLocation = "http://19.9.0.102:8080/dc/services/checkImei?wsdl")
public class WeixinCheckImeiImplService extends Service {

	private final static URL WEIXINCHECKIMEIIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.focustar.webService.WeixinCheckImeiImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.focustar.webService.WeixinCheckImeiImplService.class.getResource(".");
			url = new URL(baseUrl, "http://19.9.0.102:8080/dc/services/checkImei?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://19.9.0.102:8080/dc/services/checkImei?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEIXINCHECKIMEIIMPLSERVICE_WSDL_LOCATION = url;
	}

	public WeixinCheckImeiImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WeixinCheckImeiImplService() {
		super(WEIXINCHECKIMEIIMPLSERVICE_WSDL_LOCATION, new QName("http://impl.service.web.dc.gionee.com/", "WeixinCheckImeiImplService"));
	}

	/**
	 * 
	 * @return returns WeixinCheckImei
	 */
	@WebEndpoint(name = "WeixinCheckImeiImplPort")
	public WeixinCheckImei getWeixinCheckImeiImplPort() {
		return super.getPort(new QName("http://impl.service.web.dc.gionee.com/", "WeixinCheckImeiImplPort"), WeixinCheckImei.class);
	}

}
